name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - run: npm ci

      - run: npm run build

      # Some sanity checks:
      - name: Scripts
        run: npm run print-sha

      - run: npm test

      - run: npx eslint src/**/**.ts

      - run: npx prettier --list-different src/**/**.ts
